# Generated by Django 4.0.1 on 2022-01-10 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='active_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
